2021-08-05 13:23:53,705 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:54,306 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:54,306 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:54,311 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:54,311 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:54,899 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:54,899 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:54,903 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:54,904 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:55,486 --- tutorial.helper - WARNING - This is a warning
2021-08-05 13:23:55,487 --- tutorial.helper - ERROR - This is an error
