2021-08-05 12:15:58,282 --- tutorial.helper - ERROR - This is an error
2021-08-05 12:16:21,110 --- tutorial.helper - ERROR - This is an error
2021-08-05 12:22:12,650 --- tutorial.helper - ERROR - This is an error
2021-08-05 12:22:49,622 --- tutorial.helper - ERROR - This is an error
2021-08-05 12:22:50,935 --- tutorial.helper - ERROR - This is an error
2021-08-05 12:23:20,863 --- tutorial.helper - ERROR - This is an error
2021-08-05 12:23:20,863 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 29, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 12:26:27,310 --- tutorial.helper - ERROR - This is an error
2021-08-05 12:26:27,310 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 30, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 12:26:27,311 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 36, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:20:30,646 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:20:30,665 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 35, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:20:30,666 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 41, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:22:01,191 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:22:01,195 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:22:01,196 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:35,615 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:35,619 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:35,619 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:43,735 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:43,740 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:43,741 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:45,766 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:45,770 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:45,770 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:47,012 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:47,017 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:47,018 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:48,888 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:48,892 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:48,893 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:49,685 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:49,690 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:49,690 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:50,348 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:50,353 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:50,354 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:51,053 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:51,058 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:51,058 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:51,743 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:51,747 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:51,748 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:52,408 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:52,412 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:52,413 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:53,045 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:53,050 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:53,050 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:53,700 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:53,705 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:53,705 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:54,306 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:54,311 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:54,311 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:54,899 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:54,903 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:54,904 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:55,487 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:55,491 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:55,493 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:56,154 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:56,158 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:56,159 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:56,819 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:56,823 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:56,824 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:57,446 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:57,451 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:57,452 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 13:23:58,119 --- tutorial.helper - ERROR - This is an error
2021-08-05 13:23:58,124 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 40, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 13:23:58,125 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 46, in <module>
    a[4]
IndexError: list index out of range

2021-08-05 15:14:06,466 --- tutorial.helper - ERROR - This is an error
2021-08-05 15:14:06,481 --- tutorial.helper - ERROR - list index out of range
Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 41, in <module>
    a[4]
IndexError: list index out of range
2021-08-05 15:14:06,482 --- tutorial.helper - ERROR - An exception occurred, Traceback (most recent call last):
  File "/Volumes/HDD-Data/Users/jordi/PycharmProjects/tutorial/tutorial/helper.py", line 47, in <module>
    a[4]
IndexError: list index out of range

